2019/12/28 13:22:47.331 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:22:47.387 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 13:22:47.392 - MainThread - imsaver.py.__init__.78 - WARNING
Image saver could not create directory. Using current directory instead
[WinError 5] Access is denied: 'C:\\Users\\Lab'


2019/12/28 13:26:21.863 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:26:21.877 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 13:26:21.891 - MainThread - imsaver.py.__init__.78 - WARNING
Image saver could not create directory. Using current directory instead
[WinError 5] Access is denied: 'C:\\Users\\Lab'


2019/12/28 13:27:17.095 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:27:17.110 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 13:27:17.114 - MainThread - imsaver.py.__init__.78 - WARNING
Image saver could not create directory. Using current directory instead
[WinError 5] Access is denied: 'C:\\Users\\Lab'


2019/12/28 13:27:17.129 - MainThread - imsaver.py.__init__.78 - WARNING
Image saver could not create directory. Using current directory instead
[WinError 3] The system cannot find the path specified: 'Z:\\'


2019/12/28 13:27:17.141 - MainThread - imsaver.py.__init__.78 - WARNING
Image saver could not create directory. Using current directory instead
[WinError 3] The system cannot find the path specified: 'Z:\\'


2019/12/28 13:37:09.757 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:37:09.772 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 13:38:07.733 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:38:07.774 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 13:55:17.840 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 13:55:17.869 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 14:01:15.404 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 14:01:15.416 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 14:02:43.975 - MainThread - settingsgui.py.reset_analyses.472 - WARNING
Warning: there are 2 image indices for the 3 image analysers.



2019/12/28 14:18:05.135 - MainThread - master.py.respond.316 - WARNING
Run 0 started without camera acquisition.


2019/12/28 14:29:20.272 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 14:29:20.299 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 14:57:21.384 - MainThread - master.py.respond.317 - WARNING
Run 0 started without camera acquisition.


2019/12/28 15:26:25.286 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 15:26:25.301 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 15:27:51.347 - MainThread - settingsgui.py.reset_analyses.475 - WARNING
Warning: there are 2 image indices for the 3 image analysers.



2019/12/28 15:33:36.905 - MainThread - master.py.respond.317 - WARNING
Run 0 started without camera acquisition.


2019/12/28 15:42:55.477 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2019/12/28 15:42:55.494 - MainThread - cameraHandler.py.__init__.64 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2019/12/28 15:51:36.364 - MainThread - master.py.respond.317 - WARNING
Run 0 started without camera acquisition.


2019/12/28 15:52:45.129 - MainThread - master.py.respond.317 - WARNING
Run 0 started without camera acquisition.


2019/12/28 16:08:01.802 - Dummy-1 - networker.py.run.122 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:08:01.850 - Dummy-1 - networker.py.run.130 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:19:04.519 - Dummy-1 - networker.py.run.122 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:19:04.573 - Dummy-1 - networker.py.run.130 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:19:48.062 - Dummy-1 - networker.py.run.122 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:19:48.110 - Dummy-1 - networker.py.run.130 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:24:00.197 - Dummy-1 - networker.py.run.122 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:24:00.253 - Dummy-1 - networker.py.run.130 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:27:46.027 - Dummy-1 - networker.py.run.122 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2019/12/28 16:27:46.073 - Dummy-1 - networker.py.run.130 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


