2020/01/08 10:11:41.089 - MainThread - imsaver.py.__init__.83 - WARNING
Image saver could not create directory: X:\Sequence Log\2020\January\08
 Using current directory instead
[WinError 5] Access is denied: 'X:\\Sequence Log\\2020\\January\\08'


2020/01/08 10:15:20.549 - MainThread - runid.py.multirun_step.243 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 10:27:58.026 - MainThread - runid.py.multirun_step.243 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:00:55.026 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:10:52.598 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:15:09.216 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:15:09.323 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:17:32.306 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:18:35.876 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:18:36.013 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:20:22.070 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:45:22.462 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:45:22.625 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:47:13.520 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:50:52.421 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:50:52.526 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:52:51.084 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 11:59:14.762 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:59:14.847 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:59:15.073 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 11:59:15.253 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:00:59.949 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 12:05:24.516 - Dummy-6 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:05:24.649 - Dummy-6 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:06:01.293 - Dummy-7 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:06:44.372 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 12:13:37.540 - Dummy-7 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:13:37.639 - Dummy-7 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:14:07.135 - MainThread - runid.py.multirun_step.244 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 12:18:25.946 - Dummy-7 - networker.py.run.136 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 12:18:26.052 - Dummy-7 - networker.py.run.145 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 15:41:29.800 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/08 15:41:29.854 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/08 15:43:27.242 - MainThread - master.py.respond.353 - WARNING
Run 0 started without camera acquisition.


2020/01/08 15:44:46.105 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/08 15:44:46.165 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/08 16:40:04.429 - MainThread - runid.py.multirun_step.252 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 17:10:01.042 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/08 17:10:01.152 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/08 17:15:11.668 - MainThread - master.py.respond.353 - WARNING
Run 0 started without camera acquisition.


2020/01/08 17:15:22.827 - MainThread - master.py.respond.353 - WARNING
Run 0 started without camera acquisition.


2020/01/08 17:15:43.997 - MainThread - runid.py.multirun_step.252 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 17:20:28.121 - MainThread - master.py.respond.353 - WARNING
Run 68 started without camera acquisition.


2020/01/08 17:20:39.270 - MainThread - master.py.respond.353 - WARNING
Run 68 started without camera acquisition.


2020/01/08 17:21:04.203 - MainThread - runid.py.multirun_step.252 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 18:07:24.752 - MainThread - master.py.closeEvent.411 - WARNING
camera safe shutdown failed.
'Andor' object has no attribute 'dll'


2020/01/08 18:08:12.978 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/08 18:08:13.052 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/08 18:13:26.846 - Dummy-1 - networker.py.run.137 - ERROR
Python server: client terminated connection before message was sent. Re-inserting message at front of queue.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 18:13:26.895 - Dummy-1 - networker.py.run.146 - ERROR
Python server: client terminated connection before receive.
[WinError 10053] An established connection was aborted by the software in your host machine


2020/01/08 18:13:32.228 - MainThread - master.py.respond.353 - WARNING
Run 147 started without camera acquisition.


2020/01/08 18:13:43.181 - MainThread - runid.py.multirun_step.252 - ERROR
Multirun step could not extract user variable from table:
'NoneType' object has no attribute 'text'


2020/01/08 18:13:43.618 - MainThread - master.py.end_run.380 - WARNING
Failed to abort camera acquisition at end of run.
'Andor' object has no attribute 'dll'


2020/01/08 18:15:12.533 - MainThread - master.py.closeEvent.411 - WARNING
camera safe shutdown failed.
'Andor' object has no attribute 'dll'


